# Site settings
title : JavaChen's Blog
tagline: Sharing Technology, Recording Life
keywords : java, hadoop, hive, hbase, mapreduce, nosql, solr, solrcloud, linux, python, lua, postgresql, mysql
description: 关注开源、Java、Hadoop、NoSql、Pentaho以及数据可视化
url: "//blog.javachen.com"
author:
    name: JavaChen
    github: javachen
    email: june.chan(a)foxmail.com
    gitcafe: javachen
    twitter:
    facebook:
    googleplus:
    weibo: chenzhijun
qiniudn: //javachen.qiniudn.com
atom_path: /atom.xml
rss_path: /rss.xml

# Handling Reading
safe:         false
include:      []
exclude:      [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
keep_files:   []
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    redcarpet
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    0.0.0.0
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink: /:year/:month/:day/:title
paginate_path: /page:num
paginate: 15
timezone:    Asia/Shanghai


# Markdown Processors
redcarpet:
  extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]


# comment
comments:
  duoshuo:
    name: javachen
    rcomments:
        num: 8
        avatar: 0
        time: 0
        title: 0
        admin: 0
        length: 12
# 网站统计
analytics:
    baidu:
        siteid:         # 百度统计 js 代码后的字符串
#    51la:
#        uid: 12111481
    cnzz:
        uid: 1253501761
# blogroll
blogroll : true
brlist :
    - text : JavaChen's Blog
      url : //blog.javachen.com/
    - text : JavaChen Sitemap
      url : /sitemap.xml
    - text : Eagle's Blog
      url : //blog.jassassin.com/
    - text : 圆木菠萝罐
      url : //blog.boluotou.com/
    - text : Log4D
      url : //log4d.com/
    - text : A Java geek
      url : //blog.frankel.ch
    - text : Kohsuke Kawaguchi
      url : //kohsuke.org/
    - text : 并行实验室
      url : //www.parallellabs.com/
    - text : 灵魂机器
      url : //cn.soulmachine.me/
    - text : MayCoder
      url : //code6.github.io/
    - text : 刘兰涛的Blog
      url : //blog.liulantao.com/
    - text : zJun Blog
      url : //zjun.github.io/
